export const ActionConstants = {
	LOADING:"LOADING",
	STOP_LOADING:"STOP_LOADING",
	FETCH_SUCCESS:"FETCH_SUCCESS",
	FETCH_FAIL:"FETCH_FAIL",
	ADD_SUCCESS:"ADD_SUCCESS",
	ADD_FAIL:"ADD_FAIL",
	REMOVE_SUCCESS:"REMOVE_SUCCESS",
	REMOVE_FAIL:"REMOVE_FAIL"
}